@startuml

title __DAO's Class Diagram__\n

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.AppointmentDaoImpl {
          {static} - dateformat : DateTimeFormatter
          {static} - logger : Logger
          + loadApptData()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.BarberDaoImpl {
          + loadBarberData()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.CustomerDaoImpl {
          + loadCustomerData()
          + populateCustomerList()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.DBConnection {
          {static} - DB_URL : String
          {static} - barbers : String[]
          {static} - conn : Connection
          {static} - databaseName : String
          {static} - driver : String
          {static} - handler : DBConnection
          {static} - password : String
          {static} - stmt : Statement
          {static} - tablesExist : boolean
          {static} - username : String
          {static} + closeConnection()
          {static} + getConn()
          {static} + init()
          - DBConnection()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.PetDaoImpl {
          + getPetsByCustomer()
          + loadPetData()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.Query {
          {static} - query : String
          {static} - result : ResultSet
          {static} - stmt : Statement
          {static} + getResult()
          {static} + makeQuery()
      }
    }
  }
  

  namespace com.poshpaws.appscheduler {
    namespace dao {
      class com.poshpaws.appscheduler.dao.UserDaoImpl {
          {static} + getAllUsers()
          {static} + getUser()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
